name: Validate ARM Template

on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  id-token: write
  contents: read # or write, as needed by other parts of your workflow
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
     

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Run your action
        uses: bridgecrewio/yor-action@main

      # Step 2: Log in to Azure using a Service Principal
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Az login
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlinescript: az login

      # Step 3: Validate ARM Template Syntax using Azure CLI
      - name: Validate ARM Template Syntax
        run: |
          az deployment group validate \
            --resource-group DefaultResourceGroup-EUS \
            --template-file ./Azure_ARM_Template \
            --parameters @./Azure_ARM_Template.parameters
